cp -r values values-af
cp -r values values-be
cp -r values values-ca
cp -r values values-da
cp -r values values-et
cp -r values values-fa
cp -r values values-fi
cp -r values values-fil-rPH
cp -r values values-he
cp -r values values-hr
cp -r values values-hu
cp -r values values-in
cp -r values values-ko
cp -r values values-lt
cp -r values values-lv
cp -r values values-my
cp -r values values-nb
cp -r values values-nl
cp -r values values-ro
cp -r values values-sk
cp -r values values-sl
cp -r values values-sr
cp -r values values-sv-rSE
cp -r values values-th
cp -r values values-tl-rPH
cp -r values values-uk
